name: Sonarqube Scanner

on:
  workflow_call:
    secrets:
      sonar_token:
        required: true
      sonar_host_url:
        required: true

permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

jobs:
  sonarqube-scanner:
    # 1.1.8
    uses: Home-Office-Digital/core-cloud-workflow-sonarqube-scan/.github/workflows/sonarqube-scan.yaml@dc8836ac155426422a32235ecc4602ed533c9635
    secrets:
      sonar_token: ${{ secrets.sonar_token }}
      sonar_host_url: ${{ secrets.sonar_host_url }}
